version: '3.8'

services:
  mysql_db:
    build: .
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: exemplo_db
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456