-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.curso
(
    id_curso integer,
    nome character varying(55) NOT NULL,
    CONSTRAINT pk_curso PRIMARY KEY (id_curso)
);

CREATE TABLE IF NOT EXISTS public.aluno
(
    id_aluno integer,
    nome character varying(255) NOT NULL,
    data_nascimento date NOT NULL,
    id_responsavel integer NOT NULL,
    CONSTRAINT pk_aluno PRIMARY KEY (id_aluno)
);

CREATE TABLE IF NOT EXISTS public.responsavel
(
    id_responsavel integer,
    nome character varying(255) NOT NULL,
    CONSTRAINT pk_responsavel PRIMARY KEY (id_responsavel)
);

CREATE TABLE IF NOT EXISTS public.contato
(
    id_contato integer,
    contato character varying(55) NOT NULL,
    CONSTRAINT pk_contato PRIMARY KEY (id_contato)
);

CREATE TABLE IF NOT EXISTS public.professor
(
    id_professor integer,
    nome character varying(255) NOT NULL,
    CONSTRAINT pk_professor PRIMARY KEY (id_professor)
);

CREATE TABLE IF NOT EXISTS public.aluno_contato
(
    id_aluno integer,
    id_contato integer,
    CONSTRAINT pk_aluno_contato PRIMARY KEY (id_aluno, id_contato)
);

CREATE TABLE IF NOT EXISTS public.horario_aluno
(
    id_aluno integer,
    id_horario integer,
    CONSTRAINT pk_horario_aluno PRIMARY KEY (id_aluno, id_horario)
);

CREATE TABLE IF NOT EXISTS public.horario
(
    id_horario integer,
    inicio integer NOT NULL,
    termino integer NOT NULL,
    id_dia integer NOT NULL,
    id_professor integer NOT NULL,
    id_curso integer NOT NULL,
    CONSTRAINT pk_horario PRIMARY KEY (id_horario)
);

CREATE TABLE IF NOT EXISTS public.dia
(
    id_dia integer,
    nome character varying(55) NOT NULL,
    PRIMARY KEY (id_dia)
);

ALTER TABLE IF EXISTS public.aluno
    ADD CONSTRAINT fk_responsavel FOREIGN KEY (id_responsavel)
    REFERENCES public.responsavel (id_responsavel) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.aluno_contato
    ADD CONSTRAINT fk_aluno_contato_aluno FOREIGN KEY (id_aluno)
    REFERENCES public.aluno (id_aluno) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.aluno_contato
    ADD CONSTRAINT fk_aluno_contato_contato FOREIGN KEY (id_contato)
    REFERENCES public.contato (id_contato) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.horario_aluno
    ADD CONSTRAINT fk_horario_aluno_aluno FOREIGN KEY (id_aluno)
    REFERENCES public.aluno (id_aluno) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.horario_aluno
    ADD CONSTRAINT fk_horario_aluno_horario FOREIGN KEY (id_horario)
    REFERENCES public.horario (id_horario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.horario
    ADD CONSTRAINT fk_horario_dia FOREIGN KEY (id_dia)
    REFERENCES public.dia (id_dia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.horario
    ADD CONSTRAINT fk_horario_professor FOREIGN KEY (id_professor)
    REFERENCES public.professor (id_professor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.horario
    ADD CONSTRAINT fk_horario_curso FOREIGN KEY (id_curso)
    REFERENCES public.curso (id_curso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;